CREATE TABLE PET(
	PetID		INT				NOT NULL,
	PetName		NVARCHAR(16)	NULL,
	PetType		NVARCHAR(16)	NULL,
	PetBreed	NVARCHAR(100)	NULL,
	PetDOB		DATETIME2		NULL,
	PetWeight	FLOAT(1)		NULL,
	OwnerID		INT				NULL,
	CONSTRAINT	Pet_PetOwner_FK	FOREIGN KEY(OwnerID)
		REFERENCES PET_OWNER(OwnerID)
			ON DELETE NO ACTION,
	CONSTRAINT breedname_FK FOREIGN KEY (PetBreed) 
		REFERENCES BREED(BreedName)
);